### PR TITLE
Build package for osx

### PR DESCRIPTION
**Pull request by borchero**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
This fails with

```
aot_ceval_jit_helper.c:167:39: error: register 'r12' unsuitable for global register variables on this target
register PyObject** stack_pointer asm("r12");
                                      ^
aot_ceval_jit_helper.c:168:31: error: register 'r13' unsuitable for global register variables on this target
register PyFrameObject* f asm("r13");
                              ^
aot_ceval_jit_helper.c:169:36: error: register 'r15' unsuitable for global register variables on this target
register PyThreadState* tstate asm("r15");
```

**Comment by xhochy** [comment]
Seems like this needs a GCC compiled on macOS. This is not something we have on OSX.

**Comment by borchero** [comment]
So, bottom line: we cannot build this feedstock for OSX @xhochy?

**Comment by xhochy** [comment]
Not with reasonable effort.

**Pull request closed without merging**
